version: '2'
services:
  frontend:
    build: ./frontend/
    env_file:
      - .env
    ports:
     - '80:5000'
    depends_on:
     - redis_db

  backend:
    build: ./backend/
    env_file:
      - .env
    ports:
     - '5000:5000'
    depends_on:
     - postgresql_db

  redis_db:
    image: redis

  postgresql_db:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgresql_db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

volumes:
  postgresql_db:
    driver: local